# Loading in packages
```{r}
library(tidyverse)
library(readxl)
library(ggpubr)
library(ggsignif)
# library(xlsx)
library(ggprism)
library(openxlsx)
theme_set(theme_prism())
```

# Reading in Data
```{r}
# Reading in Data
dicty_total = read_excel(file.choose(), 
                         sheet = "Total_Cell_Output") %>% 
  mutate(Cell_Line = factor(Cell_Line, 
                            levels=c("AX2", "G120", "dDia2","VASP","mhcA"))) %>% 
  mutate(Plasmid = factor(Plasmid, 
                          levels = c("pDTi516", "pDTi571","pDTi557", "pDTi500"))) %>% 
  mutate(Transformation = factor(Transformation))


dicty_filo = read_excel(file.choose(), 
                   sheet = "Total_Filo_Output") %>% 
  mutate(Cell_Line = factor(Cell_Line, 
                            levels=c("AX2", "G120", "dDia2","VASP","mhcA"))) %>% 
    mutate(Plasmid = factor(Plasmid, 
                          levels = c("pDTi516", "pDTi571","pDTi557", "pDTi500"))) %>% 
  mutate(Transformation = factor(Transformation))

```

# Generating Summary Statistic Tables
```{r}
# Table Summaries of Data
totalcell_details = dicty_total %>% 
  mutate(Filopodia = ifelse(Filo_Number > 0,1,0)) %>%
  group_by(Cell_Line, Plasmid) %>% 
  summarize(Total_Cells= n(),
            Filopodia_Cells = sum(Filopodia == 1),
            Filopodia_Proportion = (Filopodia_Cells / Total_Cells) * 100,
            CortBody_Ratio_Avg = mean(Cortex_Body, na.rm = T),
            CortBody_Ratio_SD = sd(Cortex_Body, na.rm = T)/sqrt(Total_Cells)
            )

filopercell_details = dicty_total %>%
  group_by(Cell_Line, Plasmid) %>%
  filter(Filo_Number > 0) %>%
  summarize(Total_Cells = n(),
            FiloNum_Avg = mean(Filo_Number, na.rm = T),
            FiloNum_SD = sd(Filo_Number, na.rm = T)/sqrt(Total_Cells),
            Median_FiloNum = median(Filo_Number, na.rm = T),
            Filoper10um_Avg = mean(Filos_per_10um, na.rm = T),
            Filoper10um_sd = sd(Filos_per_10um, na.rm = T)/sqrt(Total_Cells)
            )

filo_length_details = dicty_filo %>%
  group_by(Cell_Line, Plasmid) %>%
  summarize(Total_Cells = n(),
            Filo_Length_Avg = mean(Filo_Length, na.rm =  T),
            Filo_Length_SD = sd(Filo_Length, na.rm = T)/sqrt(Total_Cells),
            Filo_Length_Median = median(Filo_Length, na.rm = T),
            Tip_Avg = mean(Filo_Body_Int, na.rm = T),
            Tip_SD = sd(Filo_Body_Int, na.rm = T)/sqrt(Total_Cells)
            )

mytable_actin = cbind(totalcell_details[1:7],
                      filopercell_details[4:8],
                      filo_length_details[4:8]) %>%
  filter(Cell_Line %in% c("AX2", "G120", "dDia2", "VASP")) %>%
  filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500"))
mytable_actin

mytable_mhcA = cbind(totalcell_details[1:7],
                     filopercell_details[4:8],
                     filo_length_details[4:8]) %>%
  filter(Cell_Line %in% c("AX2", "G120", "mhcA"))
mytable_mhcA

mytable_all = cbind(totalcell_details[1:7],
                      filopercell_details[4:8],
                      filo_length_details[4:8])


totalcell_vasp = dicty_total %>% 
  filter(ID %in% c("AC47", "PW23", "PW32", "PW33", "PW34")) %>% 
  mutate(Filopodia = ifelse(Filo_Number > 0,1,0)) %>%
  group_by(ID) %>% 
  summarize(Total_Cells= n(),
            Filopodia_Cells = sum(Filopodia == 1),
            Filopodia_Proportion = (Filopodia_Cells / Total_Cells) * 100,
            CortBody_Ratio_Avg = mean(Cortex_Body, na.rm = T),
            CortBody_Ratio_SD = sd(Cortex_Body, na.rm = T)/sqrt(Total_Cells)
            )

filopercell_vasp = dicty_total %>%
  filter(ID %in% c("AC47", "PW23", "PW32", "PW33", "PW34")) %>% 
  group_by(ID) %>%
  filter(Filo_Number > 0) %>%
  summarize(Total_Cells = n(),
            FiloNum_Avg = mean(Filo_Number, na.rm = T),
            FiloNum_SD = sd(Filo_Number, na.rm = T)/sqrt(Total_Cells),
            Median_FiloNum = median(Filo_Number, na.rm = T),
            Filoper10um_Avg = mean(Filos_per_10um, na.rm = T),
            Filoper10um_sd = sd(Filos_per_10um, na.rm = T)/sqrt(Total_Cells)
            )

filo_length_vasp = dicty_filo %>%
  filter(ID %in% c("AC47", "PW23", "PW32", "PW33", "PW34")) %>% 
  group_by(ID) %>%
  summarize(Total_Cells = n(),
            Filo_Length_Avg = mean(Filo_Length, na.rm =  T),
            Filo_Length_SD = sd(Filo_Length, na.rm = T)/sqrt(Total_Cells),
            Filo_Length_Median = median(Filo_Length, na.rm = T),
            Tip_Avg = mean(Filo_Body_Int, na.rm = T),
            Tip_SD = sd(Filo_Body_Int, na.rm = T)/sqrt(Total_Cells)
            )

mytable_vasp =  cbind(totalcell_vasp,
                      filopercell_vasp[3:7],
                      filo_length_vasp[3:7])

write.xlsx(mytable_all, file = "HMM_DataTable.xlsx")
```


```{r, echo = FALSE}
# # Rosner Outlier Test
# filonum_outliers = EnvStats::rosnerTest(dicty_total_trim$Filo_Number,
#                               k = 2)
# 
# cortexcellbody_outliers = EnvStats::rosnerTest(dicty_total$Cortex_Body,
#                                       k = 10)
# 
# filolength_outliers = EnvStats::rosnerTest(dicty_filo$Filo_Length,
#                                  k = 20)
```

```{r, echo=FALSE}
# Stats on variables

dicty_total_trim = dicty_total %>% 
  group_by(Cell_Line, Plasmid) %>%
  filter(Filo_Number > 0) %>% 
  filter(Cell_Line %in% c("mhcA", "AX2"))

dicty_filo_trim = dicty_filo %>% 
  filter(Cell_Line %in% c("mhcA", "AX2"))


# filo_num_mod = aov(Filo_Number ~  Plasmid,
#       data = dicty_total_trim)
# TukeyHSD(filo_num_mod, "Plasmid")
# 
# cortexcellbody_mod = aov(Cortex_Body ~  Plasmid,
#                          data = dicty_total_trim)
# TukeyHSD(cortexcellbody_mod, "Plasmid")
# 
# filo_length_mod = aov(Filo_Length ~  Plasmid,
#                       data = dicty_filo_trim)
# TukeyHSD(filo_length_mod, "Plasmid")

# tip_int_mod = aov(Filo_Body_Int ~  Plasmid,
#                   data = dicty_filo_trim)
# summary(tip_int_mod)
# TukeyHSD(tip_int_mod, "Plasmid")



# filo_num_mod = aov(Filo_Number ~ Cell_Line * Plasmid,
#       data = dicty_total_trim)
# TukeyHSD(filo_num_mod, "Cell_Line:Plasmid")
# 
# cortexcellbody_mod = aov(Cortex_Body ~ Cell_Line * Plasmid,
#                          data = dicty_total_trim)
# TukeyHSD(cortexcellbody_mod, "Cell_Line:Plasmid")
# 
# filo_length_mod = aov(Filo_Length ~ Cell_Line * Plasmid,
#                       data = dicty_filo_trim)
# TukeyHSD(filo_length_mod, "Cell_Line:Plasmid")
# 
tip_int_mod = aov(Filo_Body_Int ~ Cell_Line * Plasmid,
                  data = dicty_filo_trim)
TukeyHSD(tip_int_mod, "Cell_Line:Plasmid")

filoper10_mod = aov(Filos_per_10um ~ Cell_Line * Plasmid,
                  data = dicty_total_trim)
summary(filoper10_mod)
TukeyHSD(tip_int_mod, "Cell_Line:Plasmid")
```

# Graphing 

## AX2 Graphs

```{r}
ax2 = mytable_actin %>% 
  filter(Cell_Line == "AX2")

(ax2_fxnfilo = dicty_total %>%
   filter(Cell_Line %in% c("AX2")) %>% 
    filter(Filo_Number >0) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Number, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = ax2,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =ax2,
                 aes(y = FiloNum_Avg,,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("AX2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Average Filopodia Per Cell") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 25
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 32
   )
)

(ax2_cortex = dicty_total %>%
   filter(Cell_Line %in% c("AX2")) %>% 
    ggplot(aes(x = Plasmid, y = Cortex_Body, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = ax2,
              aes(y = CortBody_Ratio_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =ax2,
                 aes(y = FiloNum_Avg,,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("AX2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
    ylim(0,2.5)+
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "DdMyo7 Localization") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 1.6
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 1.8
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 2.1
   )
)

(ax2_length = dicty_filo %>%
   filter(Cell_Line %in% c("AX2")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Length, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = ax2,
              aes(y = Filo_Length_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =ax2,
                 aes(y = FiloNum_Avg,,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("AX2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Filopodial Length (um)") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 11
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 12
   )
)

(ax2_tip = dicty_filo %>%
   filter(Cell_Line %in% c("AX2")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Body_Int, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = ax2,
              aes(y = Tip_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =ax2,
                 aes(y = Tip_Avg,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("AX2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Tip:Body Intensity") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 25
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 32
   )
)
```





## G1-20
```{r}
G120 = mytable_actin %>% 
  filter(Cell_Line == "G120")

(G120_fxnfilo = dicty_total %>%
   filter(Cell_Line %in% c("G120")) %>% 
    filter(Filo_Number >0) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Number, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = G120,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =G120,
                 aes(y = FiloNum_Avg,,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("G120 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Average Filopodia Per Cell") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 28
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 20
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 32
   )
)

(G120_cortex = dicty_total %>%
   filter(Cell_Line %in% c("G120")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Cortex_Body, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = G120,
              aes(y = CortBody_Ratio_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =G120,
                 aes(y = FiloNum_Avg,,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("G120 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
    ylim(0,2.5)+
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "DdMyo7 Localization") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 1.7
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 1.6
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 2
   )
)

(G120_length = dicty_filo %>%
   filter(Cell_Line %in% c("G120")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Length, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = G120,
              aes(y = Filo_Length_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =G120,
                 aes(y = FiloNum_Avg,,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("G120 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Filopodial Length (um)") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 9.5
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black"
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 11.5
   )
)

(G120_tip = dicty_filo %>%
   filter(Cell_Line %in% c("G120")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Body_Int, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = G120,
              aes(y = Tip_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =G120,
                 aes(y = Tip_Avg,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("G120 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Tip:Body Intensity") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 14
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 18
   )
)
```

## Vasp 
```{r}
VASP = mytable_actin %>% 
  filter(Cell_Line == "VASP")

(VASP_fxnfilo = dicty_total %>%
  filter(Filo_Number >0) %>% 
   filter(Cell_Line %in% c("VASP")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Number, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = VASP,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =VASP,
                 aes(y = FiloNum_Avg,,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("VASP Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Average Filopodia Per Cell") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 10
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 15
   )
)

(VASP_cortex = dicty_total %>%
   filter(Cell_Line %in% c("VASP")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Cortex_Body, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = VASP,
              aes(y = CortBody_Ratio_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =VASP,
                 aes(y = FiloNum_Avg,,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("VASP Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
    ylim(0,2.5)+
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "DdMyo7 Localization") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 1.7
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 1.9
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 2.2
   )
)

(VASP_length = dicty_filo %>%
   filter(Cell_Line %in% c("VASP")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Length, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = VASP,
              aes(y = Filo_Length_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =VASP,
                 aes(y = FiloNum_Avg,,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("VASP Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Filopodial Length (um)") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 9
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 11
   )
)

(VASP_tip = dicty_filo %>%
   filter(Cell_Line %in% c("VASP")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Body_Int, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = VASP,
              aes(y = Tip_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =VASP,
                 aes(y = Tip_Avg,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("VASP Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Tip:Body Intensity") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 8
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 15
   )
)
```

```{r}

# Analysis of i516 by person
(VASP_filo_ID = dicty_total %>%
  filter(Filo_Number >0) %>% 
   filter(Cell_Line %in% c("VASP")) %>% 
   filter(Plasmid %in% c("pDTi516")) %>% 
    ggplot(aes(x = ID, y = Filo_Number)) +
    geom_jitter(width = 0.15,
              alpha = 0.5,
              color = "magenta") +
     geom_point(data = mytable_vasp,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =mytable_vasp,
                 aes(y = FiloNum_Avg,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("VASP Cells") +
   theme(legend.position = "bottom") +
   labs(y = "Average Filopodia Per Cell") +
    geom_signif(
     comparisons = list(c("AC47", "PW23")),
     map_signif_level = T,
     color = "black",
     y_position = 13
   ) +
   geom_signif(
     comparisons = list(c("AC47", "PW32")),
     map_signif_level = T,
     color = "black",
     y_position = 15
   ) +
    geom_signif(
     comparisons = list(c("AC47", "PW33")),
     map_signif_level = T,
     color = "black",
     y_position = 17
   ) +
   geom_signif(
     comparisons = list(c("AC47", "PW34")),
     map_signif_level = T,
     color = "black",
     y_position = 19
   ) +
   geom_signif(
     comparisons = list(c("PW23", "PW32")),
     map_signif_level = T,
     color = "black",
     y_position = 21
   ) +
    geom_signif(
     comparisons = list(c("PW23", "PW33")),
     map_signif_level = T,
     color = "black",
     y_position = 23
   ) +
   geom_signif(
     comparisons = list(c("PW23", "PW34")),
     map_signif_level = T,
     color = "black",
     y_position = 25
   ) +
    geom_signif(
     comparisons = list(c("PW32", "PW33")),
     map_signif_level = T,
     color = "black",
     y_position = 27
   ) +
    geom_signif(
     comparisons = list(c("PW32", "PW34")),
     map_signif_level = T,
     color = "black",
     y_position = 29
   ) +
    geom_signif(
     comparisons = list(c("PW33", "PW34")),
     map_signif_level = T,
     color = "black",
     y_position = 31
   )
)

# AX2 pDTi516 vs G120 i516 vs VASP i516

vasp_mini = mytable_all %>% 
  filter(Cell_Line %in% c("AX2", "G120","VASP")) %>% 
  filter(Plasmid == "pDTi516")

(vasp_i516 = dicty_total %>%
  filter(Filo_Number > 0) %>% 
   filter(Cell_Line %in% c("AX2", "G120", "VASP")) %>% 
   filter(Plasmid %in% c("pDTi516")) %>% 
    ggplot(aes(x = Cell_Line, y = Filo_Number, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
     geom_point(data = vasp_mini,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =vasp_mini,
                 aes(y = FiloNum_Avg,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("AX2 vs G120 vs VASP Cells") +
   theme(legend.position = "bottom") +
   labs(y = "Average Filopodia Per Cell",
        x = "Cell Line") +
   geom_signif(
     comparisons = list(c("AX2", "VASP")),
     map_signif_level = T,
     color = "black",
     y_position = 32
   ) +
  geom_signif(
     comparisons = list(c("AX2", "G120")),
     map_signif_level = T,
     color = "black",
     y_position = 28
   ) +
  geom_signif(
     comparisons = list(c("G120", "VASP")),
     map_signif_level = T,
     color = "black",
     y_position = 30
   )
)
```

``` {r}
dDia2 = mytable_actin %>% 
  filter(Cell_Line == "dDia2" )

(dDia2_fxnfilo = dicty_total %>%
   filter(Cell_Line %in% c("dDia2", "dDia2")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Number, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = dDia2,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =dDia2,
                 aes(y = FiloNum_Avg,,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("dDia2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Average Filopodia Per Cell") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 38
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 25
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 45
   )
)

(dDia2_cortex = dicty_total %>%
   filter(Cell_Line %in% c("dDia2")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Cortex_Body, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = dDia2,
              aes(y = CortBody_Ratio_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =dDia2,
                 aes(y = FiloNum_Avg,,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("dDia2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
    ylim(0,2.5)+
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "DdMyo7 Localization") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 1.8
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 1.5
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 2
   )
)

(dDia2_length = dicty_filo %>%
   filter(Cell_Line %in% c("dDia2")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Length, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = dDia2,
              aes(y = Filo_Length_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =dDia2,
                 aes(y = FiloNum_Avg,,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("dDia2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Filopodial Length (um)") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black"
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 11
   )
)

(dDia2_tip = dicty_filo %>%
   filter(Cell_Line %in% c("dDia2")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Body_Int, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = dDia2,
              aes(y = Tip_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =dDia2,
                 aes(y = Tip_Avg,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("dDia2 Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer GFP")) +
   labs(y = "Tip:Body Intensity") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 12
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 10
   ) +
   geom_signif(
     comparisons = list(c("pDTi516", "pDTi500")),
     map_signif_level = T,
     color = "black",
     y_position = 15
   )
)
```
## mhcA null cells
```{r}
mhcA = mytable_mhcA %>% 
  filter(Cell_Line %in% c("mhcA")) 

(mhcA_fxnfilo = dicty_total %>%
   filter(Cell_Line %in% c("mhcA")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Number, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = mhcA,
              aes(y = FiloNum_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =mhcA,
                 aes(y = FiloNum_Avg,,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("mhcA Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi557",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer mNG",
                             "Parallel Dimer GFP"),
                    guide = guide_axis(n.dodge = 2)) +
   labs(y = "Average Filopodia Per Cell") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 32
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position = 26
   ) +
    geom_signif(
     comparisons = list(c("pDTi516", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position = 38
   ) 
)

(mhcA_cortex = dicty_total %>%
   filter(Cell_Line %in% c("mhcA")) %>% 
    ggplot(aes(x = Plasmid, y = Cortex_Body, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = mhcA,
              aes(y = CortBody_Ratio_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =mhcA,
                 aes(y = FiloNum_Avg,,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("mhcA Cells") +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
    ylim(0,2.5)+
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi557",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer mNG",
                             "Parallel Dimer GFP"),
                    guide = guide_axis(n.dodge = 2)) +
   labs(y = "DdMyo7 Localization") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 1.7
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position = 1.9
   ) +
    geom_signif(
     comparisons = list(c("pDTi516", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position = 2.1
   ) 
)

(mhcA_length = dicty_filo %>%
   filter(Cell_Line %in% c("mhcA")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Length, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = mhcA,
              aes(y = Filo_Length_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =mhcA,
                 aes(y = FiloNum_Avg,,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("mhcA Cells") +
    ylim(0,12) +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi557",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer mNG",
                             "Parallel Dimer GFP"),
                    guide = guide_axis(n.dodge = 2)) +
   labs(y = "Filopodial Length (um)") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi557")),
     map_signif_level = T,
     color = "black"
   ) +
    geom_signif(
     comparisons = list(c("pDTi516", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position = 11
   ) 
)

(mhcA_tip = dicty_filo %>%
   filter(Cell_Line %in% c("mhcA")) %>% 
    ggplot(aes(x = Plasmid, y = Filo_Body_Int, color = Transformation)) +
    geom_jitter(width = 0.15,
              alpha = 0.5) +
   geom_point(data = mhcA,
              aes(y = Tip_Avg),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  size = 1.75) +
   geom_errorbar(data =mhcA,
                 aes(y = Tip_Avg,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 size = 1,
                 width = 0.15) +
   ggtitle("mhcA Cells") +
    ylim(0,15) +
   theme(axis.title.x = element_blank(),
         legend.position = "bottom") +
   scale_x_discrete(breaks = c("pDTi516",
                               "pDTi571",
                               "pDTi557",
                               "pDTi500"),
                    labels = c("FL DdMyo7",
                             "Antiparallel Dimer", 
                             "Parallel Dimer mNG",
                             "Parallel Dimer GFP"),
                    guide = guide_axis(n.dodge = 2)) +
   labs(y = "Tip:Body Intensity") +
   geom_signif(
     comparisons = list(c("pDTi571", "pDTi516")),
     map_signif_level = T,
     color = "black",
     y_position = 13
   ) +
    geom_signif(
     comparisons = list(c("pDTi571", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position = 12
   ) +
    geom_signif(
     comparisons = list(c("pDTi516", "pDTi557")),
     map_signif_level = T,
     color = "black",
     y_position =14
   ) 
)
```
## AX2 pDTi516 vs mhcA null cells 

```{r}
mhcA_AX2 = mytable_mhcA %>% 
  filter(Cell_Line %in% c("AX2", "mhcA")) %>% 
    mutate(x = ifelse(Plasmid %in% c("pDTi571", "pDTi500") & Cell_Line == "AX2", 1, 0)) %>% 
    filter(x == 0) %>% 
  filter(Plasmid %in% c("pDTi516","pDTi571", "pDTi500"))

(mhcA_AX2_fxnfilo = dicty_total %>%
    filter(Cell_Line %in% c("AX2", "mhcA")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    mutate(x = ifelse(Plasmid %in% c("pDTi571", "pDTi500") & Cell_Line == "AX2", 1, 0)) %>% 
    filter(x == 0) %>% 
    ggplot(aes(x = Cell_Line, y = Filo_Number, color =Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_AX2,
              aes(y = FiloNum_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mhcA_AX2,
                 aes(y = FiloNum_Avg,
                     group_by = Plasmid,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
   scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                      labels = c("FL DdMyo7", "Antiparallel", "Parallel"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Average Filopodia Per Cell") +
    theme(axis.title.x = element_blank(),
          legend.box.background = element_rect(color = "black"),
          legend.position = c(0.75,0.85))
)

(mhcA_AX2_filoper10 = dicty_total %>%
    filter(Cell_Line %in% c("AX2", "mhcA")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    filter(Filo_Number > 0) %>% 
    mutate(x = ifelse(Plasmid %in% c("pDTi571", "pDTi500") & Cell_Line == "AX2", 1, 0)) %>% 
    filter(x == 0) %>% 
    ggplot(aes(x = Cell_Line, y = Filos_per_10um, color =Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_AX2,
              aes(y = Filoper10um_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mhcA_AX2,
                 aes(y = Filoper10um_Avg,
                     group_by = Plasmid,
                     ymin = Filoper10um_Avg - Filoper10um_sd,
                     ymax = Filoper10um_Avg + Filoper10um_sd),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
   scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                      labels = c("FL DdMyo7", "Antiparallel", "Parallel"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Average Filopodia / 10um") +
    theme(axis.title.x = element_blank())
)

(mhcA_AX2_cortex= dicty_total %>%
     filter(Cell_Line %in% c("AX2", "mhcA")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    mutate(x = ifelse(Plasmid %in% c("pDTi571", "pDTi500") & Cell_Line == "AX2", 1, 0)) %>% 
    filter(x == 0) %>% 
    ggplot(aes(x = Cell_Line, y = Cortex_Body, color =Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_AX2,
              aes(y = CortBody_Ratio_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mhcA_AX2,
                 aes(y = CortBody_Ratio_Avg,
                     group_by = Plasmid,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
    geom_hline(yintercept = 1,
               linetype ="dashed") +
   scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                      labels = c("FL DdMyo7", "Antiparallel", "Parallel"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Cortex:Cell Body Ratio") +
    theme(axis.title.x = element_blank(),
          legend.box.background = element_rect(color = "black"),
          legend.position = c(0.75,0.85)) +
    ylim(0.5,2)
)

mhcA_AX2_filo = dicty_filo %>% 
   mutate(x = ifelse(Plasmid %in% c("pDTi571", "pDTi500") & Cell_Line == "AX2", 1, 0)) %>% 
    filter(x == 0)

(mhcA_AX2_length = mhcA_AX2_filo %>%
     filter(Cell_Line %in% c("AX2", "mhcA")) %>% 
    filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Filo_Length,
               color = Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_AX2,
              aes(y = Filo_Length_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mhcA_AX2,
                 aes(y = Filo_Length_Avg,
                     group_by = Plasmid,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                       labels = c("FL DdMyo7", "Antiparallel", "Parallel"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    theme(axis.title.x = element_blank(),
          legend.box.background = element_rect(color = "black"),
          legend.position = c(0.9,0.85)) +
    labs(y = "Filopodia Length (um)",
         x = "Cell Line")
)

(mhcA_AX2_tipint = mhcA_AX2_filo %>%
     filter(Cell_Line %in% c("AX2", "mhcA")) %>% 
    filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Filo_Body_Int,
               color = Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_AX2,
              aes(y = Tip_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mhcA_AX2,
                 aes(y = Tip_Avg,
                     group_by = Plasmid,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                       labels = c("FL DdMyo7", "Antiparallel", "Parallel"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    theme(axis.title.x = element_blank()) +
    labs(y = "Filopodia Tip:Cell Body Intensity",
         x = "Cell Line")
)
```


## pDTi516 v pDTi571 v pDTi557 v pDTi500
```{r}
mhcA_G120 = mytable_mhcA %>% 
  filter(Cell_Line  %in% c("G120", "mhcA"))

(mhcA_G120_fxnfilo = dicty_total %>%
    filter(Cell_Line %in% c("G120", "mhcA")) %>% 
    
    ggplot(aes(x = Cell_Line, y = Filo_Number, color =Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_G120,
              aes(y = FiloNum_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mhcA_G120,
                 aes(y = FiloNum_Avg,
                     group_by = Plasmid,
                     ymin = FiloNum_Avg - FiloNum_SD,
                     ymax = FiloNum_Avg + FiloNum_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
       scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                          labels = c("FL DdMyo7", "Antiparallel","Parallel mNG", "Parallel GFP"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
    labs(y = "Average Filopodia Per Cell") +
    theme(axis.title.x = element_blank(),
          legend.box.background = element_rect(color = "black"),
          legend.position = c(0.75,0.85))
)

(mhcA_G120_fxnfiloper10um = dicty_total %>%
    filter(Cell_Line %in% c("G120", "mhcA")) %>% 
    filter(Filo_Number > 0) %>% 
    ggplot(aes(x = Cell_Line, y = Filos_per_10um, color =Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_G120,
              aes(y = Filoper10um_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mhcA_G120,
                 aes(y = Filoper10um_Avg,
                     group_by = Plasmid,
                     ymin = Filoper10um_Avg - Filoper10um_sd,
                     ymax = Filoper10um_Avg + Filoper10um_sd),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
       scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                          labels = c("FL DdMyo7", "Antiparallel","Parallel mNG", "Parallel GFP"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
    labs(y = "Average Filopodia / 10um") +
    theme(axis.title.x = element_blank(),
          legend.box.background = element_rect(color = "black"),
          legend.position = c(0.75,0.85))
)

(mhcA_G120_cortex= dicty_total %>%
     filter(Cell_Line %in% c("G120", "mhcA")) %>% 
    ggplot(aes(x = Cell_Line, y = Cortex_Body, color =Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_G120,
              aes(y = CortBody_Ratio_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mhcA_G120,
                 aes(y = CortBody_Ratio_Avg,
                     group_by = Plasmid,
                     ymin = CortBody_Ratio_Avg - CortBody_Ratio_SD,
                     ymax = CortBody_Ratio_Avg + CortBody_Ratio_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
    geom_hline(yintercept = 1,
               linetype ="dashed") +
    scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                       labels = c("FL DdMyo7", "Antiparallel","Parallel mNG", "Parallel GFP"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
    labs(y = "Cortex:Cell Body Ratio") +
    theme(axis.title.x = element_blank(),
          legend.box.background = element_rect(color = "black"),
          legend.position = c(0.9,0.85)) +
    ylim(0.5,2)
)

mhcA_G120_filo = dicty_filo %>% 
  filter(Cell_Line %in% c("G120", "mhcA"))

(mhcA_G120_length = mhcA_G120_filo %>%
     filter(Cell_Line %in% c("G120", "mhcA")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Filo_Length,
               color = Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_G120,
              aes(y = Filo_Length_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mhcA_G120,
                 aes(y = Filo_Length_Avg,
                     group_by = Plasmid,
                     ymin = Filo_Length_Avg - Filo_Length_SD,
                     ymax = Filo_Length_Avg + Filo_Length_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                       labels = c("FL DdMyo7", "Antiparallel","Parallel mNG", "Parallel GFP"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
      theme(axis.title.x = element_blank(),
            legend.box.background = element_rect(color = "black"),
          legend.position = c(0.9,0.85)) +
    labs(y = "Filopodia Length (um)",
         x = "Cell Line")
)

(mhcA_G120_tipint = mhcA_G120_filo %>%
     filter(Cell_Line %in% c("G120", "mhcA")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Filo_Body_Int,
               color = Plasmid)) +
    ggforce::geom_sina(scale =F) +
   geom_point(data = mhcA_G120,
              aes(y = Tip_Avg,
                  group_by = Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mhcA_G120,
                 aes(y = Tip_Avg,
                     group_by = Plasmid,
                     ymin = Tip_Avg - Tip_SD,
                     ymax = Tip_Avg + Tip_SD),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 1,
                 width = 0.2) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                       labels = c("FL DdMyo7", "Antiparallel","Parallel mNG", "Parallel GFP"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
      theme(axis.title.x = element_blank()) +
    labs(y = "Filopodia Tip:Cell Body Intensity",
         x = "Cell Line")
)

```


# ggplots of all conditions together 

```{r}
# GGplots of Data 
(filo_per_cell_actin = dicty_total %>%
   filter(Cell_Line %in% c("AX2", "G120", "VASP", "dDia2")) %>% 
   filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    
    ggplot(aes(x = Cell_Line, y = Filo_Number, color =Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_actin,
              aes(y = mytable_actin$FiloNum_Avg,
                  group_by = mytable_actin$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mytable_actin,
                 aes(y = mytable_actin$FiloNum_Avg,
                     group_by = mytable_actin$Plasmid,
                     ymin = mytable_actin$FiloNum_Avg - mytable_actin$FiloNum_SD/sqrt(mytable_actin$Total_Cells),
                     ymax = mytable_actin$FiloNum_Avg + mytable_actin$FiloNum_SD/sqrt(mytable_actin$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
   scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Average Filopodia Per Cell",
         x = "Cell Line")
)

(filo_per_cell_mhcA = dicty_total %>%
   filter(Cell_Line %in% c("AX2", "G120", "mhcA")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    
    ggplot(aes(x = Cell_Line, y = Filo_Number, color = Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_mhcA,
              aes(y = mytable_mhcA$FiloNum_Avg,
                  group_by = mytable_mhcA$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mytable_mhcA,
                 aes(y = mytable_mhcA$FiloNum_Avg,
                     group_by = mytable_mhcA$Plasmid,
                     ymin = mytable_mhcA$FiloNum_Avg - mytable_mhcA$FiloNum_SD/sqrt(mytable_mhcA$Total_Cells),
                     ymax = mytable_mhcA$FiloNum_Avg + mytable_mhcA$FiloNum_SD/sqrt(mytable_mhcA$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
    labs(y = "Average Filopodia Per Cell",
         x = "Cell Line")
)

(cortex_actin = dicty_total %>%
   filter(Cell_Line %in% c("AX2", "G120", "VASP", "dDia2")) %>% 
    filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Cortex_Body,
               color = Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_actin,
              aes(y = mytable_actin$CortBody_Ratio_Avg,
                  group_by = mytable_actin$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mytable_actin,
                 aes(y = mytable_actin$CortBody_Ratio_Avg,
                     group_by = mytable_actin$Plasmid,
                     ymin = mytable_actin$CortBody_Ratio_Avg - mytable_actin$CortBody_Ratio_SD/sqrt(mytable_actin$Total_Cells),
                     ymax = mytable_actin$CortBody_Ratio_Avg + mytable_actin$CortBody_Ratio_SD/sqrt(mytable_actin$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Cortex:Cell Body Signal Ratio",
         x = "Cell Line")
)

(cortex_mhcA = dicty_total %>%
   filter(Cell_Line %in% c("AX2", "G120", "mhcA")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Cortex_Body,
               color = Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_mhcA,
              aes(y = mytable_mhcA$CortBody_Ratio_Avg,
                  group_by = mytable_mhcA$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mytable_mhcA,
                 aes(y = mytable_mhcA$CortBody_Ratio_Avg,
                     group_by = mytable_mhcA$Plasmid,
                     ymin = mytable_mhcA$CortBody_Ratio_Avg - mytable_mhcA$CortBody_Ratio_SD/sqrt(mytable_mhcA$Total_Cells),
                     ymax = mytable_mhcA$CortBody_Ratio_Avg + mytable_mhcA$CortBody_Ratio_SD/sqrt(mytable_mhcA$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
    labs(y = "Cortex:Cell Body Signal Ratio",
         x = "Cell Line")
)

(filolength_actin = dicty_filo %>%
   filter(Cell_Line %in% c("AX2", "G120", "VASP", "dDia2")) %>% 
    filter(Plasmid %in% c("pDTi516", "pDTi571", "pDTi500")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Filo_Length,
               color = Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_actin,
              aes(y = mytable_actin$Filo_Length_Avg,
                  group_by = mytable_actin$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mytable_actin,
                 aes(y = mytable_actin$Filo_Length_Avg,
                     group_by = mytable_actin$Plasmid,
                     ymin = mytable_actin$Filo_Length_Avg - mytable_actin$Filo_Length_SD/sqrt(mytable_actin$Total_Cells),
                     ymax = mytable_actin$Filo_Length_Avg + mytable_actin$Filo_Length_SD/sqrt(mytable_actin$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Filopodia Length (um)",
         x = "Cell Line")
)

(filolength_mhcA = dicty_filo %>%
   filter(Cell_Line %in% c("AX2", "G120", "mhcA")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    ggplot(aes(x = Cell_Line,
               y = Filo_Length,
               color = Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_mhcA,
              aes(y = mytable_mhcA$Filo_Length_Avg,
                  group_by = mytable_mhcA$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data = mytable_mhcA,
                 aes(y = mytable_mhcA$Filo_Length_Avg,
                     group_by = mytable_mhcA$Plasmid,
                     ymin = mytable_mhcA$Filo_Length_Avg - mytable_mhcA$Filo_Length_SD/sqrt(mytable_mhcA$Total_Cells),
                     ymax = mytable_mhcA$Filo_Length_Avg + mytable_mhcA$Filo_Length_SD/sqrt(mytable_mhcA$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
    scale_color_manual(breaks = c("pDTi516", "pDTi571","pDTi557", "pDTi500"),
                         values = c("#00ba39", "#609cff","#FF00FF", "#f8766d")) +
    labs(y = "Filopodia Tip:Cell Body Intensity",
         x = "Cell Line ")
)
```



```{r}
(filo_per_cell_actin = dicty_total %>%
   filter(Cell_Line %in% c("AX2", "G120", "VASP", "dDia2")) %>% 
    group_by(Cell_Line, Plasmid) %>% 
    
    ggplot(aes(x = Cell_Line, y = Filo_Number, color =Plasmid)) +
    ggforce::geom_sina(scale = F) +
   geom_point(data = mytable_actin,
              aes(y = mytable_actin$FiloNum_Avg,
                  group_by = mytable_actin$Plasmid),
                  position = position_dodge(width = 0.9),
                  color = "black",
                  alpha = 0.5,
                  size = 1.5) +
   geom_errorbar(data =mytable_actin,
                 aes(y = mytable_actin$FiloNum_Avg,
                     group_by = mytable_actin$Plasmid,
                     ymin = mytable_actin$FiloNum_Avg - mytable_actin$FiloNum_SD/sqrt(mytable_actin$Total_Cells),
                     ymax = mytable_actin$FiloNum_Avg + mytable_actin$FiloNum_SD/sqrt(mytable_actin$Total_Cells)),
                 position = position_dodge(width = 0.9),
                 color = "black",
                 alpha = 0.5,
                 size = 0.75,
                 width = 0.4) +
   scale_color_manual(breaks = c("pDTi516", "pDTi571", "pDTi500"),
                         values = c("#00ba39", "#609cff", "#f8766d")) +
    labs(y = "Average Filopodia Per Cell",
         x = "Cell Line")
)
```


